export const DEFAULT_MOMENTUM_FORM = {
  mode: 'paper',
  directionMode: 'BOTH',
  tierIndices: [1, 2, 3, 4, 5, 6],
  windowMinutes: 1,
  turnover24hMin: 100000,
  vol24hMin: 0.1,
  priceThresholdPct: 0.2,
  oiThresholdPct: 0.2,
  turnoverSpikePct: 0,
  baselineFloorUSDT: 0,
  holdSeconds: 1,
  trendConfirmSeconds: 1,
  oiMaxAgeSec: 1800,
  leverage: 10,
  marginUsd: 100,
  tpRoiPct: 5,
  slRoiPct: 5,
  entryOffsetPct: -0.01,
  cooldownMinutes: 60,
  maxNewEntriesPerTick: 5,
  entryPriceSource: 'LAST',
  globalSymbolLock: false,
};
