export const DEFAULT_MOMENTUM_FORM = {
  mode: 'paper',
  directionMode: 'BOTH',
  windowMinutes: 1,
  universeMode: 'TIERS',
  tierIndices: [],
  turnover24hMin: 100000,
  vol24hMin: 0.1,
  priceThresholdPct: 0.2,
  oiThresholdPct: 0.2,
  turnoverSpikePct: 0,
  baselineFloorUSDT: 0,
  holdSeconds: 1,
  trendConfirmSeconds: 1,
  oiMaxAgeSec: 1800,
  entryOffsetPct: -0.01,
  marginUsd: 100,
  leverage: 10,
  tpRoiPct: 5,
  slRoiPct: 5,
  singleSymbol: '',
};
