export const MOMENTUM_FIELD_META = {
  mode: { label: 'Режим торговли', help: 'paper = симуляция, demo = тестовый Bybit, real = реальный счёт. Пример: paper.' },
  directionMode: { label: 'Направление', help: 'LONG — только лонги, SHORT — только шорты, BOTH — оба направления.' },
  scanMode: { label: 'Режим скана', help: 'UNIVERSE сканирует выбранный набор символов, SINGLE работает по одному символу.' },
  universeSource: { label: 'Источник Universe', help: 'Источник списка символов из Universe Search (например TIER_1 или TIER_2).' },
  universeMode: { label: 'Режим Universe', help: 'TIERS — работать по выбранным tierIndex, SINGLE — режим одного символа.' },
  tierIndices: { label: 'Tier индексы', help: 'Мультивыбор индексов tiers из Universe Search. Пример: 1,2.' },
  singleSymbol: { label: 'Single symbol', help: 'Один символ строго из Universe list. Ручной ввод отключён.' },
  windowMinutes: { label: 'Окно расчёта', help: 'Размер окна в минутах для baseline/изменений. Допустимо: 1, 3, 5. Пример: 1.' },
  turnover24hMin: { label: 'Минимальный 24h turnover', help: 'Минимальный оборот за 24 часа в USDT для отбора символов. Пример: 100000.' },
  vol24hMin: { label: 'Минимальная 24h волатильность', help: 'Порог дневной волатильности в процентах. Пример: 0.1%.' },
  priceThresholdPct: { label: 'Порог цены', help: 'Минимальное изменение цены в окне (%), чтобы сигнал считался валидным. Пример: 0.2%.' },
  oiThresholdPct: { label: 'Порог OI', help: 'Минимальное изменение open interest в окне (%). Пример: 0.2%.' },
  turnoverSpikePct: { label: 'Порог всплеска turnover', help: 'Для LONG: насколько prevTurnover выше медианы (%). 0 = отключено. Пример: 15%.' },
  baselineFloorUSDT: { label: 'Минимальный baseline turnover', help: 'Минимальный prevTurnover (USDT) для прохождения turnover gate. Пример: 50000.' },
  holdSeconds: { label: 'Hold time', help: 'Сколько секунд сигнал должен удерживаться до входа. Пример: 3 сек.' },
  trendConfirmSeconds: { label: 'Подтверждение тренда', help: 'Сколько секунд подтверждать тренд перед входом. Пример: 5 сек.' },
  oiMaxAgeSec: { label: 'Макс. возраст OI', help: 'Максимально допустимый возраст данных OI в секундах. Пример: 1800.' },
  leverage: { label: 'Leverage', help: 'Плечо для новой сделки. Пример: 10.' },
  marginUsd: { label: 'Margin USD', help: 'Маржа одной сделки в USDT. Пример: 100.' },
  tpRoiPct: { label: 'TP ROI %', help: 'Take Profit в процентах ROI. Пример: 5%.' },
  slRoiPct: { label: 'SL ROI %', help: 'Stop Loss в процентах ROI. Пример: 5%.' },
  entryOffsetPct: { label: 'Entry offset %', help: 'Смещение цены входа относительно триггера (%). Пример: -0.01%.' },
  cooldownMinutes: { label: 'Cooldown', help: 'Пауза в минутах после закрытия позиции по символу. Пример: 60 мин.' },
  maxNewEntriesPerTick: { label: 'Макс. новых входов за тик', help: 'Лимит новых входов за один цикл сканирования. Пример: 5.' },
  entryPriceSource: { label: 'Источник цены входа', help: 'MARK или LAST — какая цена используется для расчёта входа.' },
  globalSymbolLock: { label: 'Global symbol lock', help: 'Если включено, символ блокируется глобально и не открывается повторно одновременно.' },
};
