export const MOMENTUM_FIELD_META = {
  mode: { label: 'Режим торговли', help: 'paper = симуляция, demo = тестовый Bybit, real = реальный счёт. Пример: paper.' },
  directionMode: { label: 'Направление', help: 'LONG — только лонги, SHORT — только шорты, BOTH — оба направления.' },
  tierIndices: { label: 'Tier индексы', help: 'Выберите tiers из Universe Search. По умолчанию выбраны все 1..6.' },
  windowMinutes: { label: 'Размер свечи (мин)', help: 'Допустимые значения: 1, 3, 5. Используется и в стратегии, и в инспекторе.' },
  turnover24hMin: { label: 'Минимальный 24h turnover', help: 'Минимальный оборот за 24 часа в USDT. Пример: 100000.' },
  vol24hMin: { label: 'Минимальная 24h волатильность', help: 'Порог дневной волатильности в процентах. Пример: 0.1%.' },
  priceThresholdPct: { label: 'Порог цены', help: 'Минимальное изменение цены относительно предыдущей свечи (%).' },
  oiThresholdPct: { label: 'Порог OI', help: 'Минимальное изменение open interest относительно предыдущей свечи (%).' },
  turnoverSpikePct: { label: 'Порог всплеска turnover', help: 'Насколько prevTurnover выше медианы (%). 0 = отключено.' },
  baselineFloorUSDT: { label: 'Минимальный baseline turnover', help: 'Минимальный prevTurnover (USDT) для прохождения turnover gate.' },
  holdSeconds: { label: 'Hold time', help: 'Сколько секунд сигнал удерживается перед входом.' },
  trendConfirmSeconds: { label: 'Подтверждение тренда', help: 'Сколько секунд подтверждать тренд перед входом.' },
  oiMaxAgeSec: { label: 'Макс. возраст OI', help: 'Максимально допустимый возраст данных OI (сек).' },
  leverage: { label: 'Leverage', help: 'Плечо для новой сделки.' },
  marginUsd: { label: 'Margin USD', help: 'Маржа одной сделки в USDT.' },
  tpRoiPct: { label: 'TP ROI %', help: 'Take Profit в процентах ROI.' },
  slRoiPct: { label: 'SL ROI %', help: 'Stop Loss в процентах ROI.' },
  entryOffsetPct: { label: 'Entry offset %', help: 'Смещение цены входа относительно триггера (%).' },
  cooldownMinutes: { label: 'Cooldown', help: 'Пауза в минутах после закрытия позиции по символу.' },
  maxNewEntriesPerTick: { label: 'Макс. новых входов за тик', help: 'Лимит новых входов за один цикл.' },
  entryPriceSource: { label: 'Источник цены входа', help: 'MARK или LAST — какая цена используется для расчёта входа.' },
  globalSymbolLock: { label: 'Global symbol lock', help: 'Если включено, символ блокируется глобально.' },
};
