export type PaperPendingOrder = {
  symbol: string;
  side: 'Buy' | 'Sell';
  limitPrice: number;
  qty: number;
  markAtSignal?: number;
  entryOffsetPct?: number;
  spreadBpsAtEntry?: number | null;
  placedTs: number;
  expiresTs: number;
  tpPrice?: number;
  slPrice?: number;
  orderId?: string;
  orderLinkId?: string;
  sentToExchange?: boolean;
};

export type PaperPosition = {
  symbol: string;
  side: 'LONG' | 'SHORT';
  entryPrice: number;
  markAtSignal?: number;
  entryLimit?: number;
  entryOffsetPct?: number;
  entrySlippageBpsApplied?: number;
  spreadBpsAtEntry?: number | null;
  qty: number;
  tpPrice: number;
  slPrice: number;
  openedTs: number;
  closeReason?: string;
  exitPrice?: number;
  realizedGrossPnlUSDT?: number;
  feesUSDT?: number;
  realizedNetPnlUSDT?: number;
  grossPnlUSDT?: number;
  feeTotalUSDT?: number;
  netPnlUSDT?: number;
  entryFeeUSDT?: number;
  exitFeeUSDT?: number;
  entryFeeRate?: number;
  exitFeeRate?: number;
  exitSlippageBpsApplied?: number;
  spreadBpsAtExit?: number | null;
  slippageUSDT?: number | null;
  lastPnlUSDT?: number;
};
